#ifndef DDM_MODBUS_REGISTERS_H
#define DDM_MODBUS_REGISTERS_H

#define HR_SLAVE_ADDRESS 0u
#define HR_PORT_CONFIG   1u

#define HR_CH_LEVEL_BASE   40u
#define HR_CH_LEVEL_END    43u
#define HR_CH_PERCENT_BASE 45u
#define HR_CH_PERCENT_END  48u
#define HR_CH_ON_BASE      49u
#define HR_CH_ON_END       52u

#define HR_ALL_LEVEL   53u
#define HR_ALL_PERCENT 54u
#define HR_ALL_ON      55u

#define HR_AUTO_LEVEL_BASE   60u
#define HR_AUTO_LEVEL_END    63u
#define HR_AUTO_PERCENT_BASE 64u
#define HR_AUTO_PERCENT_END  67u

#define HR_UPDATE_COMMAND   60000u
#define HR_UPDATE_STATUS    60001u
#define HR_IMAGE_SIZE_HI    60002u
#define HR_IMAGE_SIZE_LO    60003u
#define HR_IMAGE_CRC_HI     60004u
#define HR_IMAGE_CRC_LO     60005u
#define HR_IMAGE_VERSION_HI 60006u
#define HR_IMAGE_VERSION_LO 60007u
#define HR_IMAGE_OFFSET_HI  60010u
#define HR_IMAGE_OFFSET_LO  60011u
#define HR_CHUNK_WORD_COUNT 60012u
#define HR_CHUNK_DATA_BASE  60100u
#define HR_CHUNK_DATA_END   60219u
#define HR_CHUNK_MAX_WORDS  (HR_CHUNK_DATA_END - HR_CHUNK_DATA_BASE + 1u)

#define HR_FW_VERSION   9000u
#define HR_BOOT_VERSION 9001u
#define HR_DEVICE_MODE  9002u
#define HR_APP_BUILD_HI 9003u
#define HR_APP_BUILD_LO 9004u

#define UPDATE_ENTER_BOOTLOADER 0xb007u
#define UPDATE_CMD_IDLE         0x0000u
#define UPDATE_CMD_BEGIN        0x0001u
#define UPDATE_CMD_ERASE        0x0002u
#define UPDATE_CMD_WRITE_CHUNK  0x0003u
#define UPDATE_CMD_VERIFY       0x0004u
#define UPDATE_CMD_RUN_APP      0x0005u
#define UPDATE_CMD_ABORT        0x0006u

#define UPDATE_STATUS_IDLE         0u
#define UPDATE_STATUS_READY        1u
#define UPDATE_STATUS_ERASING      2u
#define UPDATE_STATUS_WRITING      3u
#define UPDATE_STATUS_VERIFYING    4u
#define UPDATE_STATUS_VALID        5u
#define UPDATE_STATUS_ERR_SIZE     100u
#define UPDATE_STATUS_ERR_BOUNDS   101u
#define UPDATE_STATUS_ERR_FLASH    102u
#define UPDATE_STATUS_ERR_CRC      103u
#define UPDATE_STATUS_ERR_IMAGE    104u
#define UPDATE_STATUS_ERR_SEQUENCE 105u
#define UPDATE_STATUS_ERR_COMMAND  106u

#define DEVICE_MODE_APPLICATION 0u
#define DEVICE_MODE_BOOTLOADER  1u

#endif
